import { Cinzel, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/general/Navbar";
import { LuInstagram } from "react-icons/lu";

const cinzel = Cinzel({
  variable: "--font-cinzel-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const sourceSans3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${sourceSans3.variable} antialiased relative`}
      >
        <Navbar />
        {children}
        <div className="fixed bottom-10 right-10 z-50">
          <div className="bg-accent p-3 rounded-full">
            <LuInstagram size={35} color="white"/>
          </div>
        </div>
      </body>
    </html>
  );
}
